### ISSUE TITLE
Terminate entire `taskGroup` process when a task fails

### ISSUE THREAD

**Issue by BibekStha** [fkrauthan/nss-run#10]
I am currently using a `taskGroup` that includes a validation task among other tasks:

`taskGroup("group", ["task1", "validationTask", "task3"]);`

When the `validationTask` fails for any reason, it terminates with the message `ELIFECYCLE Command failed with exit code 1.` However, the overall process still continues, which seems like unexpected behaviour.

The expected behaviour would be for the entire `taskGroup` process to terminate when one of the underlying tasks exits with an error. This would help ensure that the `taskGroup` execution is halted in case of a failed validation, preventing potential issues from further processing.

Please consider updating the `nss-run` package to handle task failures within a `taskGroup` by stopping the entire process when an individual task encounters an error.

**Comment by fkrauthan** [comment]
I just build a couple of examples here:

```
task('test:1', () => console.log("Test 1"));
task('test:2', () => console.log("Test 2"));
task('test:3', () => console.log("Test 3"));
task('test:4', () => console.log("Test 4"));
task('test:fail', () => Promise.reject("Not today"));

taskGroup('test-1', ["test:1", ["test:2", "test:3"], "test:4"]);
taskGroup('test-2', ["test:1", "test:fail", ["test:2", "test:3"], "test:4"]);
taskGroup('test-3', ["test:1", ["test:2", "test:fail", "test:3"], "test:4"]);
taskGroup('test-4', ["test:1", ["test:2", "test:3"], "test:fail", "test:4"]);
taskGroup('test-5', ["test:fail", "test:1", ["test:2", "test:3"], "test:4"]);

taskGroup('test-6', ["test-6.1", "test-6.2"]);
taskGroup('test-6.1', ["test:1"]);
taskGroup('test-6.2', ["test:1", ["test:2", "test:fail", "test:3"], "test:4"]);
```

Results:

| **Command** | **Tasks Executed**                                             | **Tasks Skipped**                      |
|-------------|----------------------------------------------------------------|----------------------------------------|
| `test-1`    | `test:1`; `test:2`; `test:3`; `test:4`                         | _None_                                 |
| `test-2`    | `test:1`                                                       | `test:2`; `test:3`; `test:4`           |
| `test-3`    | `test:1`; `test:2`; `test:3`                                   | `test:4`                               |
| `test-4`    | `test:1`; `test:2`; `test:3`                                   | `test:4`                               |
| `test-5`    | _None_                                                         | `test:1`; `test:2`; `test:3`; `test:4` |
| `test-6`    | `test-6.1`; `test:1`; `test-6.2`; `test:1`; `test:2`; `test:3` | `test:4`                               |
